    <link rel="stylesheet" href="{{asset('homeAssets/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('https://fonts.googleapis.com/css?family=ABeeZee')}}">
    <link rel="stylesheet" href="{{asset('https://fonts.googleapis.com/css?family=Alike+Angular')}}">
    <link rel="stylesheet" href="{{asset('https://fonts.googleapis.com/css?family=Blinker')}}">
    <link rel="stylesheet" href="{{asset('https://fonts.googleapis.com/css?family=Playfair+Display:400,700')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/fonts/fontawesome-all.min.css')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/fonts/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/fonts/fontawesome5-overrides.min.css')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/css/Accordion-with-custom-design.css')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/css/Articale-List-With-Image-Zoom.css')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/css/best-carousel-slide.css')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/css/Comment.css')}}">
    <link rel="stylesheet" href="{{asset('https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/css/styles.css')}}">
    <link rel="stylesheet" href="{{asset('homeAssets/css/survey-comment.css')}}">